#!/bin/bash

set -e

# CKAN user and database
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_POSTGRES_USER WITH PASSWORD '$CKAN_POSTGRES_USER_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
createdb --encoding=utf-8  --username=$POSTGRES_USER --owner=$CKAN_POSTGRES_USER $CKAN_POSTGRES_DB

# Read-only role for ckanext-dbquery
psql --username="$POSTGRES_USER" --command="CREATE ROLE $CKAN_DBQUERY_USER LOGIN PASSWORD '$CKAN_DBQUERY_USER_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;"
psql --username="$POSTGRES_USER" --command="GRANT CONNECT ON DATABASE $CKAN_POSTGRES_DB TO $CKAN_DBQUERY_USER;"
psql --username="$POSTGRES_USER" --dbname="$CKAN_POSTGRES_DB" --command="GRANT USAGE ON SCHEMA public TO $CKAN_DBQUERY_USER;"
psql --username="$POSTGRES_USER" --dbname="$CKAN_POSTGRES_DB" --command="GRANT SELECT ON ALL TABLES IN SCHEMA public TO $CKAN_DBQUERY_USER;"
psql --username="$POSTGRES_USER" --dbname="$CKAN_POSTGRES_DB" --command="ALTER DEFAULT PRIVILEGES FOR ROLE $CKAN_POSTGRES_USER IN SCHEMA public GRANT SELECT ON TABLES TO $CKAN_DBQUERY_USER;"
psql --username="$POSTGRES_USER" --dbname="$CKAN_POSTGRES_DB" --command="ALTER ROLE $CKAN_DBQUERY_USER SET default_transaction_read_only = on;"

# DataStore users and database
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_DATASTORE_POSTGRES_READ_USER WITH PASSWORD '$CKAN_DATASTORE_POSTGRES_READ_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_DATASTORE_POSTGRES_WRITE_USER WITH PASSWORD '$CKAN_DATASTORE_POSTGRES_WRITE_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
createdb --encoding=utf-8  --username=$POSTGRES_USER --owner=$CKAN_DATASTORE_POSTGRES_WRITE_USER $CKAN_DATASTORE_POSTGRES_DB
